# Numpy

Numpy to biblioteka wykorzystywana do obliczeń numerycznych, udostępniająca wydajne implementacje operacji na wielowymiarowych tablicach.
## Tworzenie tablic `np.array`

In [1]:
import numpy as np

A = np.array([1, 2, 3])
print(A)

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(B)

C = np.zeros(5)
print(C)

D = np.arange(5)
print(D)

E = np.arange(12).reshape(4, 3)
print(E)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0. 0. 0. 0. 0.]
[0 1 2 3 4]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Indeksowanie

In [2]:
print(A[1])

print(B[1, 1])

print(E[1:3, 1:])

2
5
[[4 5]
 [7 8]]


## Operacje na tablicach numpy
Większość operacji na tablicach numpy jest zwektoryzowanych - działają poszczególnych na elementach tablic, a nie całych tablicach.

In [3]:
X = np.arange(1, 10).reshape(3, 3)
Y = np.arange(10, 19).reshape(3, 3)
print("X:\n", X)
print("Y:\n", Y)
print("X + Y:\n", X + Y)
print("X * Y:\n", X * Y)
print("X / Y:\n", X / Y)
print("X @ Y:\n", X @ Y)

X:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Y:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
X + Y:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
X * Y:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
X / Y:
 [[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
X @ Y:
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [4]:
print("np.log(X):\n", np.log(X))
print("np.exp(X):\n", np.exp(X))
print("np.sin(X):\n", np.sin(X))

np.log(X):
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
np.exp(X):
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
np.sin(X):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [5]:
print("np.sum(X):\n", np.sum(X))
print("np.prod(X):\n", np.prod(X))
print("np.min(X):\n", np.min(X))
print("np.max(X):\n", np.max(X))

np.sum(X):
 45
np.prod(X):
 362880
np.min(X):
 1
np.max(X):
 9


In [6]:
X = list(np.random.randn(10**6))

In [7]:
%%timeit
sum(X)

26 ms ± 2.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
X = np.random.randn(10**6)

In [9]:
%%timeit
np.sum(X)

209 µs ± 9.44 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Pandas: podstawy

## Tworzenie `DataFrame`
`DataFrame` możemy stworzyć procedurą `pd.DataFrame()` podając `dict` zawierający kolumny, lub dwuwymiarową strukturę danych ([więcej informacji](https://pandas.pydata.org/docs/user_guide/dsintro.html#dataframe)). Alternatywą jest wczytanie z pliku, np. `pd.read_csv()`.

In [10]:
import pandas as pd
fruit = pd.DataFrame({"fruit": ["Apple", "Banana", "Orange"], "weight": [98.2, 116.5, 138.9], "kcal": [52, 88, 66]})
fruit

fruit  weight  kcal
0   Apple    98.2    52
1  Banana   116.5    88
2  Orange   138.9    66

In [11]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
df1 = pd.DataFrame(np.arange(11, 20).reshape(3,3))
df1

0   1   2
0  11  12  13
1  14  15  16
2  17  18  19

In [13]:
mtcars = pd.read_csv("mtcars.csv") # Source: R (https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/mtcars)
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

## Sprawdzanie zawartości `DataFrame`
`pandas` zawiera kilka użytecznych funkcji, które pozwalają wstępnie zbadać zawartość `DataFrame`:
- `df.head()` - wyświetla kilka pierwszych wierszy,
- `df.info()` - podaje informacje o kolumnach,
- `df.describe()` - podaje statystyki opisowe dotyczące kolumn. 

In [14]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [15]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [16]:
mtcars.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

Domyślnie, `describe()` podaje tylko statystyki dotyczące kolumn numerycznych. Możemy otrzymać też statystyki dla kolumn nienumerycznych podając `include='all'` lub `include='object`.

In [17]:
mtcars.describe(include='all')

model        mpg        cyl        disp          hp       drat  \
count          32  32.000000  32.000000   32.000000   32.000000  32.000000   
unique         32        NaN        NaN         NaN         NaN        NaN   
top     Mazda RX4        NaN        NaN         NaN         NaN        NaN   
freq            1        NaN        NaN         NaN         NaN        NaN   
mean          NaN  20.090625   6.187500  230.721875  146.687500   3.596563   
std           NaN   6.026948   1.785922  123.938694   68.562868   0.534679   
min           NaN  10.400000   4.000000   71.100000   52.000000   2.760000   
25%           NaN  15.425000   4.000000  120.825000   96.500000   3.080000   
50%           NaN  19.200000   6.000000  196.300000  123.000000   3.695000   
75%           NaN  22.800000   8.000000  326.000000  180.000000   3.920000   
max           NaN  33.900000   8.000000  472.000000  335.000000   4.930000   

               wt       qsec         vs         am       gear     carb  
count   32.000000  32.000000  32.000000  32.000000  32.000000  32.0000  
unique        NaN        NaN        NaN        NaN        NaN      NaN  
top           NaN        NaN        NaN        NaN        NaN      NaN  
freq          NaN        NaN        NaN        NaN        NaN      NaN  
mean     3.217250  17.848750   0.437500   0.406250   3.687500   2.8125  
std      0.978457   1.786943   0.504016   0.498991   0.737804   1.6152  
min      1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%      2.581250  16.892500   0.000000   0.000000   3.000000   2.0000  
50%      3.325000  17.710000   0.000000   0.000000   4.000000   2.0000  
75%      3.610000  18.900000   1.000000   1.000000   4.000000   4.0000  
max      5.424000  22.900000   1.000000   1.000000   5.000000   8.0000

In [18]:
mtcars.describe(include='object')

model
count          32
unique         32
top     Mazda RX4
freq            1

## Indeksowanie
### Wybieranie kolumn
Pojedyncze kolumny lub zbiory kolumn można wybierać na kilka sposobów:

In [19]:
mtcars.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [20]:
mtcars["mpg"]

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [21]:
mtcars[["mpg", "wt", "hp"]]

mpg     wt   hp
0   21.0  2.620  110
1   21.0  2.875  110
2   22.8  2.320   93
3   21.4  3.215  110
4   18.7  3.440  175
5   18.1  3.460  105
6   14.3  3.570  245
7   24.4  3.190   62
8   22.8  3.150   95
9   19.2  3.440  123
10  17.8  3.440  123
11  16.4  4.070  180
12  17.3  3.730  180
13  15.2  3.780  180
14  10.4  5.250  205
15  10.4  5.424  215
16  14.7  5.345  230
17  32.4  2.200   66
18  30.4  1.615   52
19  33.9  1.835   65
20  21.5  2.465   97
21  15.5  3.520  150
22  15.2  3.435  150
23  13.3  3.840  245
24  19.2  3.845  175
25  27.3  1.935   66
26  26.0  2.140   91
27  30.4  1.513  113
28  15.8  3.170  264
29  19.7  2.770  175
30  15.0  3.570  335
31  21.4  2.780  109

## Wybieranie wierszy
Wiersze możemy wybierać także za pomocą operatora `[]` podając zakresy `low:high`.

In [22]:
mtcars[3:4]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
3  Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   

   carb  
3     1

In [23]:
mtcars[0:5]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

## Wybieranie wierszy i kolumn
Zakresy wierszy i kolumn możemy wybierać za pomocą:
- `loc[]` - wybieramy za pomocą nazw
- `iloc[]` - wybieramy za pomocą indeksów liczbowych.

Przykładowo, wybierzmy wiersze 0-4 i kolumny `mpg`, `cyl`, `disp`.

In [24]:
mtcars.loc[0:4, "mpg":"disp"]

mpg  cyl   disp
0  21.0    6  160.0
1  21.0    6  160.0
2  22.8    4  108.0
3  21.4    6  258.0
4  18.7    8  360.0

In [25]:
mtcars.iloc[0:5, 1:4]

mpg  cyl   disp
0  21.0    6  160.0
1  21.0    6  160.0
2  22.8    4  108.0
3  21.4    6  258.0
4  18.7    8  360.0

Zwróćmy uwagę, że w `loc[]` podajemy zakresy domknięte, a w `iloc[]` otwarte. Możliwe jest też pominięcie jednej lub obu stron zakresu. W `loc[]` możemy podać też listę wierszy lub kolumn.

In [26]:
mtcars.loc[:4, :"hp"]

model   mpg  cyl   disp   hp
0          Mazda RX4  21.0    6  160.0  110
1      Mazda RX4 Wag  21.0    6  160.0  110
2         Datsun 710  22.8    4  108.0   93
3     Hornet 4 Drive  21.4    6  258.0  110
4  Hornet Sportabout  18.7    8  360.0  175

In [27]:
mtcars.loc[:, ["mpg", "hp"]]

mpg   hp
0   21.0  110
1   21.0  110
2   22.8   93
3   21.4  110
4   18.7  175
5   18.1  105
6   14.3  245
7   24.4   62
8   22.8   95
9   19.2  123
10  17.8  123
11  16.4  180
12  17.3  180
13  15.2  180
14  10.4  205
15  10.4  215
16  14.7  230
17  32.4   66
18  30.4   52
19  33.9   65
20  21.5   97
21  15.5  150
22  15.2  150
23  13.3  245
24  19.2  175
25  27.3   66
26  26.0   91
27  30.4  113
28  15.8  264
29  19.7  175
30  15.0  335
31  21.4  109

## Indeksy
Etykiety wierszy i kolumn `DataFrame` przechowywane są w indeksach. Domyślnie, wczytując plik, pandas interpretuje pierwszy wiersz jako etykiety kolumn, a dla wierszy tworzy indeks liczbowy.

In [28]:
mtcars.columns # Index zawiera etykiety kolumn

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [29]:
mtcars.index # Index zawiera etykiety wierszy

RangeIndex(start=0, stop=32, step=1)

Indeks wierszy nie musi być numeryczny. Mogą to być nazwy, lub np. daty. Jako indeks możemy wykorzystać jedną z kolumn, w tym przypadku `model`.

In [30]:
mtcars = mtcars.set_index("model")
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
model                    
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

Teraz w `loc[]` możemy podać nazwę modelu.

In [31]:
mtcars.loc["Merc 240D":"Merc 450SLC"]

mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
model                                                                   
Merc 240D    24.4    4  146.7   62  3.69  3.19  20.0   1   0     4     2
Merc 230     22.8    4  140.8   95  3.92  3.15  22.9   1   0     4     2
Merc 280     19.2    6  167.6  123  3.92  3.44  18.3   1   0     4     4
Merc 280C    17.8    6  167.6  123  3.92  3.44  18.9   1   0     4     4
Merc 450SE   16.4    8  275.8  180  3.07  4.07  17.4   0   0     3     3
Merc 450SL   17.3    8  275.8  180  3.07  3.73  17.6   0   0     3     3
Merc 450SLC  15.2    8  275.8  180  3.07  3.78  18.0   0   0     3     3

Możemy przywrócić domyślny indeks za pomocą `reset_index()`. Stary indeks zostanie zachowany jako kolumna.

In [32]:
mtcars = mtcars.reset_index()
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

## Filtrowanie
Oprócz wybierania przy użyciu etykiet (`loc[]`) i indeksów liczbowych (`iloc[]`) pandas umożliwia także wybieranie przy użyciu wektorów binarnych (typu `bool`) o długości równej liczbie wierszy (lub kolumn). Wybrane zostaną te wiersze (lub kolumny), dla których w wektorze znajdzie się `True`. Umożliwia to filtrowanie danych względem zadanego kryterium. Przykładowo, wybrać wszystkie samochody dla których `hp >= 200` można w następujący sposób:

In [33]:
mtcars[mtcars.hp >= 200]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
6      3     4  
14     3     4  
15     3     4  
16     3     4  
23     3     4  
28     5     4  
30     5     8

W powyższym przykładzie, `mtcars.hp >= 200` tworzy wektor binarny, który następnie wykorzystuje do indeksowania `DataFrame`.

In [34]:
vec = mtcars.hp >= 200
vec

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27    False
28     True
29    False
30     True
31    False
Name: hp, dtype: bool

In [35]:
mtcars[vec]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
6      3     4  
14     3     4  
15     3     4  
16     3     4  
23     3     4  
28     5     4  
30     5     8

Operacja `>=` jest **zwektoryzowana**, tak jak większość operacji na `DataFrame` i `Series`. To znaczy, że wykonywana jest na każdym elemencie ciągu, a nie na ciągu jako całości. Zwracaną wartością także jest ciąg. Podobnie działają np. operacje arytmetyczne. Przykładowo, poniższa operacja tworzy ciąg zawierający liczbę km/tonę dla każdego samochodu:

In [36]:
mtcars.hp / mtcars.wt

0     41.984733
1     38.260870
2     40.086207
3     34.214619
4     50.872093
5     30.346821
6     68.627451
7     19.435737
8     30.158730
9     35.755814
10    35.755814
11    44.226044
12    48.257373
13    47.619048
14    39.047619
15    39.638643
16    43.030870
17    30.000000
18    32.198142
19    35.422343
20    39.350913
21    42.613636
22    43.668122
23    63.802083
24    45.513654
25    34.108527
26    42.523364
27    74.686054
28    83.280757
29    63.176895
30    93.837535
31    39.208633
dtype: float64

Jeśli chcemy uwzględnić wiele kryteriów filtrowania, możemy wykorzystać operacje logiczne `&`, `|`, `~`. Uwaga: korzystamy tu z operatorów bitowych, a nie zwykłych (niezwektoryzowanych) operatorów logicznych (`and`, `or`, `not`). W poniższym przykładzie wybierzemy samochody o mocy powyżej 100 KM i wadze poniżej 3.5 t:

In [37]:
mtcars[(mtcars.hp >= 100) & (mtcars.wt < 3.5)]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0           Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1       Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
3      Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4   Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5             Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
9            Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10          Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
22        AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
27       Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28     Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29       Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
31         Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
3      3     1  
4      3     2  
5      3     1  
9      4     4  
10     4     4  
22     3     2  
27     5     2  
28     5     4  
29     5     6  
31     4     2

## Typy danych
Podstawowe typy danych obsługiwane przez pandas to:
- `int64` - liczby całkowite,
- `float64` - liczby zmiennoprzecinkowe,
- `bool` - wartości logiczne `True`/`False`
- `datetime64` - daty
- `object` - zwykle przechowuje `str` (napisy), ale może przechowywać obiekty dowolnego typu, lub różnych typów.
Więcej informacji na temat typów danych znajduje się w [dokumentacji](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes).

Typy danych możemy sprawdzić w następujący sposób:

In [38]:
mtcars.dtypes

model     object
mpg      float64
cyl        int64
disp     float64
hp         int64
drat     float64
wt       float64
qsec     float64
vs         int64
am         int64
gear       int64
carb       int64
dtype: object

## Operacje na napisach
Operacje na napisach dostępne są po wybraniu danej kolumny a następnie `.str`. Przykładowo, aby zmienić nazwy modeli na wielkie litery, mogę użyć następującej metody:

In [39]:
mtcars.model.str.upper().head(10)

0            MAZDA RX4
1        MAZDA RX4 WAG
2           DATSUN 710
3       HORNET 4 DRIVE
4    HORNET SPORTABOUT
5              VALIANT
6           DUSTER 360
7            MERC 240D
8             MERC 230
9             MERC 280
Name: model, dtype: object

Pełna lista dostępnych operacji znajduje się [tutaj](https://pandas.pydata.org/docs/reference/series.html#string-handling).
Przydatne są zwłaszcza operacje pozwalające filtrować przy użyciu RegEx. Na przykład, w następujący sposób można wybrać wszystkie Mercedesy i Mazdy:

In [40]:
mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]

/var/folders/mc/zh86xrrn7bn5z5x4bd29xgp40000gn/T/ipykernel_40151/518579333.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]


model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0       Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1   Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
7       Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8        Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9        Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
10      Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
11     Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3   
12     Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3   
13    Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3   

    carb  
0      4  
1      4  
7      2  
8      2  
9      4  
10     4  
11     3  
12     3  
13     3

## Dodawanie i usuwanie danych
### Dodawanie kolumn
Nowe kolumny możemy tworzyć w następujący sposób:

In [41]:
mtcars["n_wheels"] = 4
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  n_wheels  
0     4         4  
1     4         4  
2     1         4  
3     1         4  
4     2         4

W powyższym przykładzie przypisujemy nowej kolumnie przypisujemy wartość skalarną, która jest propagowana na wszystkie wiersze.
Możemy też stworzyć nową kolumnę z Series lub innej sekwencji:

In [42]:
mtcars["hp_per_ton"] = mtcars.hp / mtcars.wt
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  n_wheels  hp_per_ton  
0     4         4   41.984733  
1     4         4   38.260870  
2     1         4   40.086207  
3     1         4   34.214619  
4     2         4   50.872093

### Usuwanie wierszy i kolumn
Wiersze i kolumny możemy usuwać metodą `drop()` podając jako argument listę etykiet. 

In [43]:
mtcars.drop([0, 1, 2]).head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   

   carb  n_wheels  hp_per_ton  
3     1         4   34.214619  
4     2         4   50.872093  
5     1         4   30.346821  
6     4         4   68.627451  
7     2         4   19.435737

W poniższym przykładzie usuwane są wszystkie Mercedesy i Mazdy:

In [44]:
merc_maz = mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]
mtcars = mtcars.drop(merc_maz.index)
mtcars.head()

/var/folders/mc/zh86xrrn7bn5z5x4bd29xgp40000gn/T/ipykernel_40151/1444433062.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  merc_maz = mtcars[mtcars.model.str.contains("(Merc)|(Mazda)")]


model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   

   carb  n_wheels  hp_per_ton  
2     1         4   40.086207  
3     1         4   34.214619  
4     2         4   50.872093  
5     1         4   30.346821  
6     4         4   68.627451

Kolumny usuwamy dodając parametr `axis='columns'` lub `axis=1`.

In [45]:
mtcars.drop(["n_wheels", "hp_per_ton"], axis='columns').head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   

   carb  
2     1  
3     1  
4     2  
5     1  
6     4

### Dodawanie wierszy
Wiersze najlepiej dodawać metodą `pd.concat()`.

In [46]:
mtcars = pd.concat([mtcars, merc_maz])
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   

    gear  carb  n_wheels  hp_per_ton  
2      4     1         4   40.086207  
3      3     1         4   34.214619  
4      3     2         4   50.872093  
5      3     1         4   30.346821  
6      3     4         4   68.627451  
14     3     4         4   39.047619  
15     3     4         4   39.638643  
16     3     4         4   43.030870  
17     4     1         4   30.000000  
18     4     2         4   32.198142  
19     4     1         4   35.422343  
20     3     1         4   39.350913  
21     3     2         4   42.613636  
22     3     2         4   43.668122  
23     3     4         4   63.802083  
24     3     2         4   45.513654  
25     4     1         4   34.108527  
26     5     2         4   42.523364  
27     5     2         4   74.686054  
28     5     4         4   83.280757  
29     5     6         4   63.176895  
30     5     8         4   93.837535  
31     4     2         4   39.208633  
0      4     4         4   41.984733  
1      4     4         4   38.260870  
7      4     2         4   19.435737  
8      4     2         4   30.158730  
9      4     4         4   35.755814  
10     4     4         4   35.755814  
11     3     3         4   44.226044  
12     3     3         4   48.257373  
13     3     3         4   47.619048

Nowe wiersze zostały dodane na końcu. Ponieważ zachowane zostały wartości indeksu, można przywrócić pierwotną kolejność sortując względem indeksu:

In [47]:
mtcars = mtcars.sort_index()
mtcars

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  n_wheels  hp_per_ton  
0      4     4         4   41.984733  
1      4     4         4   38.260870  
2      4     1         4   40.086207  
3      3     1         4   34.214619  
4      3     2         4   50.872093  
5      3     1         4   30.346821  
6      3     4         4   68.627451  
7      4     2         4   19.435737  
8      4     2         4   30.158730  
9      4     4         4   35.755814  
10     4     4         4   35.755814  
11     3     3         4   44.226044  
12     3     3         4   48.257373  
13     3     3         4   47.619048  
14     3     4         4   39.047619  
15     3     4         4   39.638643  
16     3     4         4   43.030870  
17     4     1         4   30.000000  
18     4     2         4   32.198142  
19     4     1         4   35.422343  
20     3     1         4   39.350913  
21     3     2         4   42.613636  
22     3     2         4   43.668122  
23     3     4         4   63.802083  
24     3     2         4   45.513654  
25     4     1         4   34.108527  
26     5     2         4   42.523364  
27     5     2         4   74.686054  
28     5     4         4   83.280757  
29     5     6         4   63.176895  
30     5     8         4   93.837535  
31     4     2         4   39.208633

# Zadania
### Zadanie 1
Plik `SP500.csv` zawiera ceny otwarcia (`Open`), zamknięcia (`Close`), minimalną (`Low`), maksymalną (`High`) oraz wolumen obrotów (`Volume`) indeksu S&P 500 w latach 2018-2022.

1. Wczytaj plik jako `DataFrame` metodą `pd.read_csv()`.
2. Zbadaj zawartość metodami `head()`, `info()`, `describe()`.
3. Wybieranie:
    - Wybierz tylko kolumnę `Close`.
    - Wybierz kolumny `Date`, `Open`, `Close`
    - Wybierz 30. dzień notowań.
    - Wybierz 30 pierwszych dni notowań.
    - Wybierz ceny otwarcia i zamknięcia dla 30 pierwszych dni notowań.
4. Filtrowanie:
    - Znajdź dni, w których cena minimalna nie przekroczyła 2800.
    - Znajdź dni, w których wolumen obrotów przekroczył 2 500 000 000 a cena minimalna nie przekroczyła 3000.
    - Znajdź dni, w których wartość indeksu osiągnęła najwyższą i najniższą wartość. Wskazówka: skorzystaj z funkcji `max()` i `min()`.
    - Znajdź dni, w których cena otwarcia przekroczyła średnią cenę otwarcia. Wskazówka: skorzystaj z funkcji `mean()`.
5. Dodawanie i usuwanie:
    - Stwórz nową kolumnę zawierającą różnicę między ceną maksymalną a minimalną danego dnia.
    - Stwórz nową kolumnę zawierającą odchylenie ceny otwarcia od średniej ceny otwarcia.
    - Usuń kolumnę `Volume`.
    - Usuń wiersze zawierające notowania z roku 2018.
    - W pliku `SP500Jan2023.csv` znajdują się dane ze stycznia 2023. Wczytaj go i dodaj zawartość do zbioru. Pamiętaj o kolumnach dodanych i usuniętych we wcześniejszych podpunktach. Co dzieje się w przypadku braku zgodności kolumn? Sprawdź w dokumentacji [`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat), który parametr kontroluje to, co metoda robi w tej sytuacji.

### Zadanie 2
Wczytaj zbiory w plikach `life_expectancy_years.csv` i `housing.csv`. Eksploruj je za pomocą poznanych metod. Zanotuj swoje obserwacje.
